version: '3.3'
services:
    wifioverbt:
        restart: unless-stopped
        privileged: true
        container_name: aicare/wifi_over_bt 
        devices:
            - "/dev/wlan0:/dev/wlan0"
        network_mode: host
        volumes:
            - './service:/etc/systemd/system/dbus-org.bluez.service:ro'
            - './start.sh:/start.sh'
        image: 'aicare/wifioverbt:1.0'
